[test]
levels = ["install", "registration", "instantiation", "execution", "javascript"]
publish = true

[test.workflows]
cpu = []
cuda = "all"

[test.platforms]
platforms = ["linux_cuda", "windows_cuda", "windows_portable_cuda", "windows_desktop_cuda"]
