[project]
name = "comfyui-sam3dobjects"
description = "ComfyUI wrapper for SAM3DObjects: extract 3D meshes/gaussians from pictures"
version = "0.1.8"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/PozzettiAndrea/ComfyUI-SAM3DObjects"

[tool.comfy]
PublisherId = "pznodes"
DisplayName = "SAM3DObjects"
Icon = ""
