[project]
name = "comfyui-sam3dobjects"
description = "Warning, uses experimental package `comfy-env` to attempt a one click isolated install. Will download and use pixi package manager. ComfyUI wrapper for SAM3DObjects: extract 3D meshes/gaussians from pictures"
version = "0.1.19"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/PozzettiAndrea/ComfyUI-SAM3DObjects"

[tool.comfy]
PublisherId = "pznodes"
DisplayName = "SAM3DObjects"
Icon = "https://raw.githubusercontent.com/PozzettiAndrea/ComfyUI-SAM3DObjects/main/assets/icon.png"
