python = "3.12"

[cuda]
packages = ["pytorch3d", "gsplat", "nvdiffrast", "flash-attn", "sageattention", "spconv", "cumm"]

[dependencies]
av = "*"
numpy = ">=1.24.0"
pillow = ">=10.0.0"
scipy = ">=1.11.0"
matplotlib = ">=3.9.0"
pyvista = ">=0.43.0"
pyopengl = ">=3.1.0"
psutil = ">=5.9.0"

[pypi-dependencies]
comfy-aimdo = "*"
hydra-core = ">=1.3.2"
easydict = ">=1.13"
loguru = ">=0.7.2"
utils3d = { git = "https://github.com/EasternJournalist/utils3d.git", rev = "3913c65d81e05e47b9f367250cf8c0f7462a0900" }
trimesh = "*"
open3d = ">=0.18.0"
xatlas = ">=0.0.9"
pymeshfix = ">=0.16.0"
plyfile = "*"
pyrender = ">=0.1.45"
opencv-python-headless = ">=4.9.0"
scikit-image = ">=0.23.1"
timm = ">=0.9.16"
huggingface-hub = "*"
python-igraph = ">=1.0.0"
tqdm = "*"
optree = ">=0.11.0"
lightning = ">=2.0.0"
comfy-sparse-attn = "*"